// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoclickController from "./autoclick_controller"
application.register("autoclick", AutoclickController)

import CurrentController from "./current_controller"
application.register("current", CurrentController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import UploadController from "./upload_controller"
application.register("upload", UploadController)
